name: Build and deploy .NET Core application to Azure Web App

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: BookingAPIpracadomowa
  AZURE_WEBAPP_PACKAGE_PATH: ./publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ./Booking.API/Booking.API.csproj

      - name: Build
        run: dotnet build ./Booking.API/Booking.API.csproj --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test ./Booking.API/Booking.API.csproj --no-build

      - name: Publish
        run: dotnet publish ./Booking.API/Booking.API.csproj --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.BookingAPIpracadomowa_88C0 }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
